# Project properties
pluginGroup = com.christiangennari
pluginName = Free AI Commit Message
pluginVersion = 0.1.7
pluginSinceBuild = 241
pluginUntilBuild =

# Java & Kotlin
javaVersion = 17
kotlin.stdlib.default.dependency = false

# Gradle options
org.gradle.jvmargs = -Xmx2g -XX:+UseG1GC
org.gradle.parallel = true
org.gradle.caching = true
